[package]
name = "wow-db2-proc-macros"
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
convert_case = "0"
itertools.workspace = true
proc-macro2 = "1"
quote = "1"
syn = "2"
