[package]
name = "wow-db2"
version = "0.0.0"
edition = "2021"

[dependencies]
byteorder = "1"
flagset.workspace = true
itertools.workspace = true
num.workspace = true
serde.workspace = true
sqlx.workspace = true
thiserror.workspace = true
