[package]
name = "skeleton-module"
version = "0.0.0"
edition = "2021"

[dependencies]
# Local crates
azothacore-common.workspace = true
azothacore-server.workspace = true
# External crates
bevy.workspace = true
tracing.workspace = true
serde.workspace = true
tokio.workspace = true
